# Generated by Django 4.2.7 on 2026-01-21 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('international_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('chile_zone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Beach',
                'verbose_name_plural': 'Beaches',
                'unique_together': {('name', 'city', 'country')},
            },
        ),
        migrations.CreateModel(
            name='LitterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='snake_case identifier, e.g. plastic_fragment', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Human readable label', max_length=255)),
            ],
            options={
                'verbose_name': 'Litter Type',
                'verbose_name_plural': 'Litter Types',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SamplingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('organization', models.CharField(max_length=255)),
                ('total_items', models.IntegerField()),
                ('total_items_per_m2', models.FloatField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_events', to='litter.beach')),
            ],
            options={
                'verbose_name': 'Sampling Event',
                'verbose_name_plural': 'Sampling Events',
                'ordering': ['-date'],
                'unique_together': {('beach', 'date', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='LitterCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('litter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='litter.littertype')),
                ('sampling_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litter_counts', to='litter.samplingevent')),
            ],
            options={
                'verbose_name': 'Litter Count',
                'verbose_name_plural': 'Litter Counts',
                'unique_together': {('sampling_event', 'litter_type')},
            },
        ),
    ]
