# Generated by Django 4.2.7 on 2026-01-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingevent',
            name='total_items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplingevent',
            name='total_items_per_m2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
