# Generated by Django 4.2.7 on 2026-02-02 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def seed_default_sampling_method(apps, schema_editor):
    SamplingMethod = apps.get_model("litter", "SamplingMethod")
    SamplingEvent = apps.get_model("litter", "SamplingEvent")

    # Create a deterministic default method for legacy data
    method, _ = SamplingMethod.objects.get_or_create(
        code="grid_quadrats_v1",
        defaults={
            "name": "Grid Quadrats (Transect x Station)",
            "description": "Default method for legacy imported events (MVP).",
            "default_params_schema": {
                "n_transects": {"type": "int", "default": 2, "min": 1},
                "n_stations": {"type": "int", "default": 6, "min": 1},
                "unit_area_m2": {"type": "float", "default": 9.0, "min": 0.0001},
            },
            "unit_template": {
                "unit_kind": "quadrat",
                "layout": "transect_station_grid",
                "transects": {"param": "n_transects", "default": 2},
                "stations_per_transect": {"param": "n_stations", "default": 6},
                "area_m2": {"param": "unit_area_m2", "default": 9.0},
                "label_format": "T{transect}-S{station}",
            },
        },
    )

    # Force all existing events to reference the created method
    SamplingEvent.objects.all().update(sampling_method=method)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('litter', '0002_alter_samplingevent_total_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_params_schema', models.JSONField(blank=True, null=True)),
                ('unit_template', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SamplingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sampling/photos/')),
                ('photo_kind', models.CharField(choices=[('evidence', 'Evidence'), ('site', 'Site'), ('context', 'Context')], default='evidence', max_length=16)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SamplingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_kind', models.CharField(choices=[('quadrat', 'Quadrat'), ('belt_segment', 'Belt segment'), ('segment', 'Segment'), ('photo_quadrat', 'Photo quadrat'), ('other', 'Other')], default='quadrat', max_length=32)),
                ('transect_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('station_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('zone', models.CharField(choices=[('intertidal', 'Intertidal'), ('wrack_line', 'Wrack line'), ('backshore', 'Backshore'), ('dune', 'Dune'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('area_m2', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sampling_event_id', 'transect_no', 'station_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UnitLitterCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='littercount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='littercount',
            name='litter_type',
        ),
        migrations.RemoveField(
            model_name='littercount',
            name='sampling_event',
        ),
        migrations.AlterModelOptions(
            name='beach',
            options={},
        ),
        migrations.AlterModelOptions(
            name='littertype',
            options={'ordering': ['sort_order', 'label']},
        ),
        migrations.AlterModelOptions(
            name='samplingevent',
            options={'ordering': ['-date', 'beach__name']},
        ),
        migrations.RenameField(
            model_name='samplingevent',
            old_name='total_items_per_m2',
            new_name='event_area_m2',
        ),
        migrations.RenameField(
            model_name='samplingevent',
            old_name='total_items',
            new_name='event_total_items',
        ),
        migrations.AlterUniqueTogether(
            name='beach',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='samplingevent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='beach',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='beach',
            name='beach_type',
            field=models.CharField(choices=[('sandy', 'Sandy'), ('rocky', 'Rocky'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='beach',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='beaches/covers/'),
        ),
        migrations.AddField(
            model_name='beach',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beach',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beach',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='littertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='littertype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='littertype',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='littertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='event_density_items_per_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='method_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sampling_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sampling_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='units_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='units_expected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='beach',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beach',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beach',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='littertype',
            name='code',
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='littertype',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samplingevent',
            name='beach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='litter.beach'),
        ),
        migrations.AlterField(
            model_name='samplingevent',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='beach',
            index=models.Index(fields=['country', 'region', 'name'], name='litter_beac_country_f3419e_idx'),
        ),
        migrations.AddIndex(
            model_name='samplingevent',
            index=models.Index(fields=['status', 'date'], name='litter_samp_status_b94ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='samplingevent',
            index=models.Index(fields=['beach', 'date'], name='litter_samp_beach_i_614ea6_idx'),
        ),
        migrations.DeleteModel(
            name='LitterCount',
        ),
        migrations.AddField(
            model_name='unitlittercount',
            name='litter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_counts', to='litter.littertype'),
        ),
        migrations.AddField(
            model_name='unitlittercount',
            name='sampling_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='litter.samplingunit'),
        ),
        migrations.AddField(
            model_name='samplingunit',
            name='sampling_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='litter.samplingevent'),
        ),
        migrations.AddField(
            model_name='samplingphoto',
            name='sampling_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='litter.samplingevent'),
        ),
        migrations.AddField(
            model_name='samplingphoto',
            name='sampling_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='litter.samplingunit'),
        ),
        migrations.AddField(
            model_name='samplingphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sampling_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='samplingevent',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='samplingevent',
            name='organization',
        ),
        migrations.AddField(
            model_name="samplingevent",
            name="sampling_method",
            field=models.ForeignKey(
                to="litter.samplingmethod",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(seed_default_sampling_method, noop_reverse),

        migrations.AddConstraint(
            model_name='unitlittercount',
            constraint=models.UniqueConstraint(fields=('sampling_unit', 'litter_type'), name='uq_unitlittercount_unit_type'),
        ),
        migrations.AddConstraint(
            model_name='samplingunit',
            constraint=models.UniqueConstraint(fields=('sampling_event', 'unit_kind', 'transect_no', 'station_no'), name='uq_samplingunit_event_kind_transect_station'),
        ),
    ]
