# Generated by Django 4.2.7 on 2026-02-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litter', '0003_samplingmethod_samplingphoto_samplingunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingevent',
            name='sampling_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='litter.samplingmethod'),
        ),
    ]
