# Generated by Django 4.2.7 on 2026-02-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litter', '0005_organization_samplingevent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='region_chile',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
