# Generated by Django 4.2.7 on 2024-06-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_titulo_post_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='iimagen',
            new_name='imagen',
        ),
    ]
