# Generated by Django 4.2.7 on 2024-06-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores_kg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastico_pesca_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('plastico_uso_domestico_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cuerdas_y_cordeles_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vidrios_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('latas_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('textil_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('papel_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('neumaticos_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('id_indicadores_kg', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores_un',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastico_pesca_un', models.IntegerField(null=True)),
                ('plastico_uso_domestico_un', models.IntegerField(null=True)),
                ('cuerdas_y_cordeles_un', models.IntegerField(null=True)),
                ('vidrios_un', models.IntegerField(null=True)),
                ('latas_un', models.IntegerField(null=True)),
                ('textil_un', models.IntegerField(null=True)),
                ('papel_un', models.IntegerField(null=True)),
                ('neumaticos_un', models.IntegerField(null=True)),
                ('id_indicadores_un', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True)),
                ('fecha_monitoreo', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('monitor', models.CharField(blank=True, max_length=50)),
                ('lugar', models.CharField(blank=True, max_length=50)),
                ('tipo_monitoreo', models.CharField(blank=True, max_length=50)),
                ('usuario_id', models.CharField(blank=True, max_length=50)),
                ('monitoreo_id', models.CharField(blank=True, max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(null=True)),
                ('apellido', models.CharField(blank=True, max_length=50)),
                ('contacto', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('identificacion', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('passsword', models.CharField(blank=True, max_length=50)),
                ('rol', models.CharField(blank=True, max_length=50)),
                ('usuario', models.CharField(blank=True, max_length=50)),
                ('usuario_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
