# Generated by Django 4.2.7 on 2024-06-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_alter_monitoreo_latitud_alter_monitoreo_longitud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicadores_kg',
        ),
        migrations.DeleteModel(
            name='Indicadores_un',
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='cuerdas_y_cordeles_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='cuerdas_y_cordeles_un',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='id_indicadores_kg',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='id_indicadores_un',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='latas_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='latas_un',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='neumaticos_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='neumaticos_un',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='papel_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='papel_un',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='plastico_pesca_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='plastico_pesca_un',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='plastico_uso_domestico_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='plastico_uso_domestico_un',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='textil_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='textil_un',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='vidrios_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='vidrios_un',
            field=models.IntegerField(null=True),
        ),
    ]
